//Next.
import type { Metadata } from "next";
//Utils(Typography).
import { Poppins, Rubik } from "next/font/google";
//Tailwind.
import "./globals.css";
import { ThemeProvider } from "next-themes";

//Typography.
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

//Metadata.
export const metadata: Metadata = {
  title: "Web App Starter Template",
  description: "Generated by Dylan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} ${rubik.variable} font-sans antialiased bg-background text-foreground`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
