//Next.
import type { Metadata, Viewport } from "next";
//Utils(Typography).
import { Poppins, Rubik } from "next/font/google";
//Tailwind.
import "./globals.css";
import { ThemeProvider } from "next-themes";
// Service Worker Registration
import SwRegister from "./sw-register";

//Typography.
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

//Metadata.
export const metadata: Metadata = {
  title: "Web App Starter Template",
  description: "Generated by Dylan",
  manifest: "/manifest.json",
  formatDetection: {
    telephone: false,
  },
  icons: {
    icon: "/icons/icon-192x192.png",
    apple: "/icons/icon-192x192.png",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Web App Starter",
  },
};

// Viewport (Next.js 15+ recommendation)
export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="application-name" content="Web App Starter" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Web App Starter" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="msapplication-tap-highlight" content="no" />
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
      </head>
      <body
        className={`${poppins.variable} ${rubik.variable} font-sans antialiased bg-background text-foreground`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Service Worker Registration Component */}
          <SwRegister />
          <main className="">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}